# docker registry in which the images are hosted
registry: "" # docker-registry.com

# list of images

aggregator:
  repository: reportportal/landing-aggregator
  tag: latest
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 160m
      memory: 256Mi

# aggregator settings

landing:
  port: 8080
  twitter_consumer:
  twitter_consumer_secret:
  twitter_token:
  twitter_token_secret:
  twitter_buffer_size: 10
  twitter_search_term: 
  github_include_beta: 
  github_token:
  youtube_channel_id:
  youtube_buffer_size: 15
  google_api_key:
  
ingress:
  hosts:
    - status.reportportal.com
  annotations:
    kubernetes.io/ingress.class: nginx
  tls: []
  # - hosts:
  #   - status.reportportal.com
  #   secretName: status.reportportal.com-tls
    
# node selector for all components, if any
nodeSelector:
  enabled: false
  selector:
    reportportal: true