# @param registry - Docker registry
registry: ""

aggregator:
  repository: reportportal/landing-aggregator
  tag: 1.46.1
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 160m
      memory: 256Mi

# @param secretName if is not provided, the values will be taken from the @param landing
secretName: ""

landing:
  port: 8080
  contentful:
    space_id:
    token:
  twitter:
    consumer:
    consumer_secret: 
    token:
    token_secret:
    buffer_size: 10
    search_term: "@ReportPortal_io"
  github_include_beta:
  github_token:
  youtube:
    channel_id:
    buffer_size: 15
  google_api_key:
  mailchimp:
    api_key:
    user: landing-aggregator
    timeout_seconds: 3
  
ingress:
  hosts:
    - status.k8s.com
  annotations:
    kubernetes.io/ingress.class: nginx
  tls: []
  # - hosts:
  #   - status.reportportal.com
  #   secretName: status.reportportal.com-tls
    
# node selector for all components, if any
nodeSelector:
  enabled: false
  selector:
    reportportal: true