apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aggregator
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reportportal-aggregator
  serviceName: aggregator
  template:
    metadata:
      labels:
        component: reportportal-aggregator
    spec:
      containers:
      - env:
        - name: "PORT"
          value: "{{ .Values.landing.port }}"
        {{- if .Values.secretName }}
        - name: "CONTENTFUL_SPACE_ID"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: contentful_space_id
        - name: "CONTENTFUL_TOKEN"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: contentful_token
        - name: "TWITTER_CONSUMER"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: twitter_consumer
        - name: "TWITTER_CONSUMER_SECRET"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: twitter_consumer_secret
        - name: "TWITTER_TOKEN"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: twitter_token
        - name: "TWITTER_TOKEN_SECRET"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: twitter_token_secret
        - name: "GITHUB_TOKEN"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: github_token
        - name: "YOUTUBE_CHANNEL_ID"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: youtube_channel_id
        - name: "GOOGLE_API_KEY"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: google_api_key
        - name: "MAILCHIMP_API_KEY"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: mailchimp_api_key
        {{- else }}
        - name: CONTENTFUL_SPACE_ID
          value: "{{ .Values.landing.contentful.space_id }}"
        - name: CONTENTFUL_TOKEN
          value: "{{ .Values.landing.contentful.token }}"
        - name: "TWITTER_CONSUMER"
          value: "{{ .Values.landing.twitter.consumer }}"
        - name: "TWITTER_CONSUMER_SECRET"
          value: "{{ .Values.landing.twitter.consumer_secret }}"
        - name: "TWITTER_TOKEN"
          value: "{{ .Values.landing.twitter.token }}"
        - name: "TWITTER_TOKEN_SECRET"
          value: "{{ .Values.landing.twitter.token_secret }}"
        - name: "TWITTER_BUFFER_SIZE"
          value: "{{ .Values.landing.twitter.buffer_size }}"
        - name: "TWITTER_SEARCH_TERM"
          value: "{{ .Values.landing.twitter.search_term}}"
        - name: "GITHUB_INCLUDE_BETA"
          value: "{{ .Values.landing.github_include_beta }}"
        - name: "GITHUB_TOKEN"
          value: "{{ .Values.landing.github_token }}"
        - name: "YOUTUBE_BUFFER_SIZE"
          value: "{{ .Values.landing.youtube.buffer_size }}"
        - name: "YOUTUBE_CHANNEL_ID"
          value: "{{ .Values.landing.youtube.channel_id }}"
        - name: "GOOGLE_API_KEY"
          value: "{{ .Values.landing.google_api_key }}"
        - name: "MAILCHIMP_API_KEY"
          value: "{{ .Values.landing.mailchimp.api_key }}"
        - name: "MAILCHIMP_USER"
          value: "{{ .Values.landing.mailchimp.user }}"
        - name: "MAILCHIMP_TIMEOUT_SECONDS"
          value: "{{ .Values.landing.mailchimp.timeout_seconds }}"
            {{- end }}
        image: "{{ .Values.aggregator.repository }}:{{ .Values.aggregator.tag }}"
        name: aggregator
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.aggregator.resources.requests.cpu }}
            memory: {{ .Values.aggregator.resources.requests.memory }}
          limits:
            cpu: {{ .Values.aggregator.resources.limits.cpu }}
            memory: {{ .Values.aggregator.resources.limits.memory }}
